# Generated by Django 4.2.20 on 2025-05-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_for_desktop', models.ImageField(upload_to='banners/desktop')),
                ('image_for_mobile', models.ImageField(upload_to='banners/desktop')),
                ('status', models.BooleanField(default=True)),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white')], default='black', max_length=10)),
            ],
        ),
    ]
