# Generated by Django 4.2.20 on 2025-05-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrollingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scrolling-image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scrolling-image',
                'verbose_name_plural': 'Scrolling-images',
                'ordering': ['-created_at'],
            },
        ),
    ]
