# Generated by Django 4.2.20 on 2025-05-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_products',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
