# Generated by Django 4.2.20 on 2025-06-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_explore_the_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explore_the_range',
            options={'ordering': ['name'], 'verbose_name_plural': 'Explore the Range'},
        ),
    ]
