# Generated by Django 4.2.20 on 2025-06-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_explore_the_range_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explore_the_range',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='explore_the_range',
            name='description',
        ),
        migrations.RemoveField(
            model_name='explore_the_range',
            name='image',
        ),
        migrations.RemoveField(
            model_name='explore_the_range',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='explore_the_range',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='explore_the_range',
            name='status',
        ),
        migrations.RemoveField(
            model_name='explore_the_range',
            name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='explore_the_range',
            name='total_products',
        ),
    ]
