# Generated by Django 4.2.20 on 2025-06-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_explore_the_range_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Explore_the_range',
        ),
    ]
