# Generated by Django 4.2.20 on 2025-06-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_productimage_color_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_for_desktop',
            field=models.FileField(upload_to='banners/desktop'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_for_mobile',
            field=models.FileField(upload_to='banners/desktop'),
        ),
    ]
