# Generated by Django 4.2.20 on 2025-06-24 10:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_product_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='small_description',
        ),
    ]
