# Generated by Django 4.2.20 on 2025-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_accordion_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(choices=[('in_stock', 'In Stocki'), ('out_of_stock', 'Out Of Stock')], default='in_stock'),
        ),
    ]
