# Generated by Django 4.2.20 on 2025-06-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out Of Stock')], default='in_stock', max_length=225),
        ),
    ]
