# Generated by Django 4.2.20 on 2025-06-26 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_videoproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproduct',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoproduct',
            name='product_image',
            field=models.FileField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='videoproduct',
            name='video',
            field=models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'avi', 'mov', 'mkv', 'flv', 'wmv', 'mpeg', 'mpg'])]),
        ),
    ]
