# Generated by Django 4.2.20 on 2025-06-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
