# Generated by Django 4.2.20 on 2025-06-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
    ]
